name: Test jq utility

on: workflow_dispatch

jobs:
  jq-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check jq version
        run: jq -h

      - name: Checkout
        uses: actions/checkout@4

      - name: Check file before compression
        run: cat ./public/data/db.json

      - name: Compress db.json
        run: jq -c . ./public/data/db.json > ./public/data/db.tmp

      - name: Replace db.json
        run: mv ./public/data/db.tmp ./public/data/db.json

      - name: Check file after compression
        run: cat ./public/data/db.json
